StuDocs/Models/PrijavaZaIspit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StuDocs.Models
{
    public class PrijavaZaIspit
    {
        [Key()]
        [Display(Name = "iKnow број на пријавата")]
        //[Required()]
        public string iknowBroj { get; set; }

        [Display(Name = "Факултет")]
        public string faculty { get; set; }

        [Display(Name = "Циклус на студии")]
        public string ciklus { get; set; }

        [Display(Name = "Студиска програма")]
        public string programa { get; set; }

        [Display(Name = "Модул")]
        public string modul { get; set; }

        [Display(Name = "Испитен рок")]
        public string ispitenRok { get; set; }

        [Display(Name = "Учебна година")]
        public uint uchebna { get; set; }

        [Display(Name = "Предмет")]
        [Required()]
        public string predmet { get; set; }

        [Display(Name = "Код на предметот")]
        public string kod { get; set; }

        [Display(Name = "Семестар и учебна година кога се слуша предметот")]
        public string semestar { get; set; }

        [Display(Name = "Кредити")]
        public uint krediti { get; set; }

        [Display(Name = "По кој пат се полага испитот")]
        public string polaganje { get; set; }

        [Display(Name = "Професор")]
        public string prof { get; set; }

        [Display(Name = "Асистент")]
        public string assistant { get; set; }

        [Display(Name = "Шифра за административна такса")]
        public string adminTaksa { get; set; }

    }
}

StuDocs/Controllers/PrijavaZaIspitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StuDocs.Models;

namespace StuDocs.Controllers
{
    public class PrijavaZaIspitsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PrijavaZaIspits
        public ActionResult Index()
        {
            return View(db.PrijavaZaIspits.ToList());
        }

        // GET: PrijavaZaIspits/Details/5
        public ActionResult Details() //string id
        {
            PrijavaZaIspit prijavaZaIspit = TempData["prijava"] as PrijavaZaIspit;
            Student student = TempData["Student"] as Student;

            TempData["Student"] = student;
            TempData["prijava"] = prijavaZaIspit;

            if (prijavaZaIspit == null)
            {
                return HttpNotFound();
            }
            return View(prijavaZaIspit);
        }

        // GET: PrijavaZaIspits/Create
        public ActionResult Create()
        {
            Student student = TempData["Student"] as Student;
            return View();
        }

        public ActionResult Print()
        {
            PrijavaStudent prijava = new PrijavaStudent();
            prijava.p = TempData["prijava"] as PrijavaZaIspit;
            prijava.s = TempData["student"] as Student;
            return View(prijava);
        }

        // POST: PrijavaZaIspits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iknowBroj,faculty,ciklus,programa,modul,ispitenRok,predmet,kod,semestar,polaganje,prof,assistant,adminTaksa")] PrijavaZaIspit prijavaZaIspit)
        {
            if (ModelState.IsValid)
            {
                Student student = TempData["student"] as Student;

                TempData["student"] = student;
                TempData["prijava"] = prijavaZaIspit;

                return RedirectToAction("Details");
            }
            return View(prijavaZaIspit);
        }

        // GET: PrijavaZaIspits/Edit/5
        public ActionResult Edit() //string id
        {
            Student student = TempData["student"] as Student;
            PrijavaZaIspit prijavaZaIspit = TempData["prijava"] as PrijavaZaIspit;
            if (prijavaZaIspit.iknowBroj == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (prijavaZaIspit == null)
            {
                return HttpNotFound();
            }
            TempData["student"] = student;
            TempData["prijava"] = prijavaZaIspit;
            return View(prijavaZaIspit);
        }

        // POST: PrijavaZaIspits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iknowBroj,faculty,ciklus,programa,modul,ispitenRok,predmet,kod,semestar,polaganje,prof,assistant,adminTaksa")] PrijavaZaIspit prijavaZaIspit)
        {
            Student student = TempData["student"] as Student;
            if (ModelState.IsValid)
            {
                
                TempData["prijava"] = prijavaZaIspit;
                return RedirectToAction("Details");
            }
            TempData["student"] = student;
            return View(prijavaZaIspit);
        }

















        //----------------------------------------------------------------------------------------

        // GET: PrijavaZaIspits/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrijavaZaIspit prijavaZaIspit = db.PrijavaZaIspits.Find(id);
            if (prijavaZaIspit == null)
            {
                return HttpNotFound();
            }
            return View(prijavaZaIspit);
        }

        // POST: PrijavaZaIspits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PrijavaZaIspit prijavaZaIspit = db.PrijavaZaIspits.Find(id);
            db.PrijavaZaIspits.Remove(prijavaZaIspit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StuDocs/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StuDocs.Models;

namespace StuDocs.Controllers
{
    public class StudentsController : Controller
    {

        // GET: Students/Details/5
        public ActionResult Details() //Student st
        {
            Student s = TempData["Student"] as Student;
            return View(s);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, specific properties you want to bind to are enabled
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "embg,name,surname,parentName,email,nationality,birthAddress,homeAddress,birthDate,phone")] Student stud)
        {
            TempData["Student"] = stud;
            if(stud.embg == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            else
                return RedirectToAction("Details"); //, new { s = stud }
        }

        // GET: Students/Edit/5
        public ActionResult Edit() //Student s
        {
            Student s = TempData["Student"] as Student;
            if (s.embg == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "embg,name,surname,parentName,email,nationality,birthAddress,homeAddress,birthDate,phone")] Student stud)
        {
            TempData["Student"] = stud;

            return RedirectToAction("Details"); //, new { s = stud }

        }



        //------------------------------------------------------------------------------------------

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Students
        public ActionResult Index()
        {
            return View(db.Students.ToList());
        }

        // GET: Students/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StuDocs/Views/PrijavaZaIspits/Create.cshtml
@model StuDocs.Models.PrijavaZaIspit

@{
    ViewBag.Title = "Create";
}

<h2>Нова пријава за испит</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Пополнете ги сите информации подолу</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.iknowBroj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iknowBroj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iknowBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.faculty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.faculty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.faculty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ciklus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ciklus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ciklus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.programa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.programa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.programa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modul, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modul, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modul, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ispitenRok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ispitenRok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ispitenRok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.predmet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.predmet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.predmet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.semestar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.semestar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.semestar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.polaganje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.polaganje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.polaganje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prof, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prof, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prof, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assistant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assistant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assistant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adminTaksa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adminTaksa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adminTaksa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@{ 
    TempData["prijava"] = Model;
    StuDocs.Models.Student student = TempData["student"] as StuDocs.Models.Student;
    TempData["student"] = student;
}
<div>
    @Html.ActionLink("Назад", "Details", "Students", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StuDocs/Views/PrijavaZaIspits/Delete.cshtml
@model StuDocs.Models.PrijavaZaIspit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PrijavaZaIspit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.faculty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.faculty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ciklus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ciklus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.programa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.programa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modul)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modul)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ispitenRok)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ispitenRok)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.predmet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.predmet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.semestar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.semestar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.polaganje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.polaganje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prof)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prof)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assistant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assistant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adminTaksa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adminTaksa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StuDocs/Views/PrijavaZaIspits/Details.cshtml
@model StuDocs.Models.PrijavaZaIspit

@{
    ViewBag.Title = "Преглед";
    StuDocs.Models.Student student = TempData["student"] as StuDocs.Models.Student;
}

<h2>Преглед на внесените информации</h2>

<div>
    <h4>Пријава за испит по предметот @Html.DisplayFor(model => model.predmet)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.faculty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.faculty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ciklus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ciklus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.programa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.programa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modul)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modul)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ispitenRok)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ispitenRok)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.predmet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.predmet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.semestar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.semestar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.polaganje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.polaganje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prof)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prof)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assistant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assistant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adminTaksa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adminTaksa)
        </dd>

    </dl>
</div>
<p>
    <a class="btn btn-default" href=@Url.Action("Print", "PrijavaZaIspits", null) target="_blank">Пополни пријава за испит &raquo;</a>
</p>
<p>
    @{
        TempData["student"] = student;
        TempData["prijava"] = Model;
    }
    @Html.ActionLink("Измени", "Edit") <!-- new { id = Model.iknowBroj }--> |
    @Html.ActionLink("Откажи", "Details", "Students", null, null)
</p>

StuDocs/Views/PrijavaZaIspits/Edit.cshtml
@model StuDocs.Models.PrijavaZaIspit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PrijavaZaIspit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.iknowBroj)

        <div class="form-group">
            @Html.LabelFor(model => model.faculty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.faculty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.faculty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ciklus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ciklus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ciklus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.programa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.programa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.programa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modul, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modul, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modul, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ispitenRok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ispitenRok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ispitenRok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.predmet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.predmet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.predmet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.semestar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.semestar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.semestar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.polaganje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.polaganje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.polaganje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prof, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prof, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prof, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assistant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assistant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assistant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adminTaksa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adminTaksa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adminTaksa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StuDocs/Views/PrijavaZaIspits/Index.cshtml
@model IEnumerable<StuDocs.Models.PrijavaZaIspit>

@{
    ViewBag.Title = "Index";
}

<h2>Попис</h2>

<p>
    @Html.ActionLink("Нов студент", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.faculty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ciklus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.programa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.modul)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ispitenRok)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.predmet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.semestar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.polaganje)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prof)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.assistant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adminTaksa)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.faculty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ciklus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.programa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.modul)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ispitenRok)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.predmet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.semestar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.polaganje)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prof)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.assistant)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.adminTaksa)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.iknowBroj }) |
            @Html.ActionLink("Details", "Details", new { id=item.iknowBroj }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.iknowBroj })
        </td>
    </tr>
}

</table>